name: sd-caso-practico-comunicacion

services:
  inventoryservice:
    image: ${DOCKER_REGISTRY-}inventoryservice
    build:
      context: .
      dockerfile: src/Services/InventoryService/Dockerfile

  ordersservice:
    image: ${DOCKER_REGISTRY-}ordersservice
    build:
      context: .
      dockerfile: src/Services/OrdersService/Dockerfile

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"