services:
  inventoryservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "5001:8080"

  ordersservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - Services__InventoryApi__BaseUrl=http://inventoryservice:8080
      - RabbitMQ__HostName=rabbitmq 
    ports:
      - "5000:8080"

  notificationservice:
    environment:
      - DOTNET_ENVIRONMENT=Development
      - RabbitMQ__HostName=rabbitmq 
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
